stages:
  - dependencies
  - lint
  - test
  - package_deploy
  - deploy

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

.pnpm_common:
  stage: deps
  image: node:18-alpine
  tags:
    - nsfw-1
  before_script:
    - echo -en "\nDOMAIN=$DOMAIN\nSUBDOMAIN=$SUBDOMAIN\n" > .env.local
    - cat "$ENV" >> .env.local
    - source .env.local
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - npm install -g pnpm
    - node -v && npm -v && pnpm -v
    - >
      [ -d ~/.pnpm-store ] || mkdir -p ~/.pnpm-store
    - pnpm config set store-dir ~/.pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

lint:
  extends: .pnpm_common
  stage: lint
  script:
    - pnpm lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
      changes:
        - '**/*.{js,jsx,ts,tsx,css}'
        - '.eslintrc.json'
        - '.eslintignore'
        - '.stylelintrc.json'
        - '.stylelintignore'
        - 'prettier.config.js'
        - '.prettierignore'
        - 'package.json'
        - 'pnpm-lock.yaml'
        - 'tsconfig.json'
        - '.gitlab-ci.yml'
  when: on_success
  timeout: 10 minutes

# test:
#   extends: .pnpm_common
#   stage: lint
#   script:
#     - pnpm test
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#       when: on_success
#       changes:
#         - '**/*.{js,jsx,ts,tsx,css}'
#         - 'package.json'
#         - 'pnpm-lock.yaml'
#         - 'tsconfig.json'
#         - '.gitlab-ci.yml'
#   when: on_success
#   timeout: 10 minutes

package_deploy:
  image: docker/compose
  stage: package_deploy
  tags:
    - nsfw-1
  before_script:
    - echo -en "\nDOMAIN=$DOMAIN\nSUBDOMAIN=$SUBDOMAIN\n" > .env.local && cat "$ENV" >> .env.local && source .env.local
    - cp .env.local .env
    - docker info
    - docker-compose version
    - docker-compose config
    - docker-compose ps
    - sh ./scripts/ci/notify.sh "🚀 DEPLOY"
  script:
    - docker-compose --env-file .env.local up -d --build
  after_script:
    - >
      if [[ $CI_JOB_STATUS == 'success' ]]; then
        sh ./scripts/ci/notify.sh "✅ DEPLOYED"
      elif [[ $CI_JOB_STATUS == 'canceled' ]]; then
        sh ./scripts/ci/notify.sh "⚠️ DEPLOYED"
      elif [[ $CI_JOB_STATUS == 'failed' ]]; then
        sh ./scripts/ci/notify.sh "❌ DEPLOYED"
        exit 1
      else
        sh ./scripts/ci/notify.sh "❓ UNKNOWN CI_JOB_STATUS"
        exit 1
      fi
  environment:
    name: production
    url: https://aiko.icu
    on_stop: stop
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success

# stop
stop:
  stage: package_deploy
  image: docker/compose
  tags:
    - nsfw-1
  script:
    - docker-compose --env-file .env.local down
    - sh ./scripts/ci/notify.sh "✋ STOPPED"
  when: manual
  environment:
    name: production
    action: stop
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
