version: '3.7'

networks:
  aikoicu:
    driver: bridge
  proxy:
    external: true

services:
  aikoicu-db-test:
    image: postgres:15.3-alpine
    container_name: aikoicu-db-test
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_DATA: ${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
    ports:
      - 5432:5432
    volumes:
      - /mnt/cloud/aikoicu/db:/var/lib/postgresql/data:rw
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=50'
      - '-c'
      - 'shared_buffers=1GB'
      - '-c'
      - 'effective_cache_size=4GB'
      - '-c'
      - 'work_mem=16MB'
      - '-c'
      - 'maintenance_work_mem=512MB'
      - '-c'
      - 'random_page_cost=1.1'
      - '-c'
      - 'temp_file_limit=10GB'
      - '-c'
      - 'log_min_duration_statement=200ms'
      - '-c'
      - 'idle_in_transaction_session_timeout=10s'
      - '-c'
      - 'lock_timeout=1s'
      - '-c'
      - 'statement_timeout=60s'
      - '-c'
      - 'shared_preload_libraries=pg_stat_statements'
      - '-c'
      - 'pg_stat_statements.max=10000'
      - '-c'
      - 'pg_stat_statements.track=all'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - aikoicu
    labels:
      - traefik.tcp.routers.aikoicu-db-test.entrypoints=postgres
      - traefik.tcp.routers.aikoicu-db-test.tls=true
      - traefik.tcp.routers.aikoicu-db-test.tls.certresolver=${CERT_RESOLVER}
      - traefik.tcp.routers.aikoicu-db-test.service=aikoicu-db-test
      - traefik.tcp.services.aikoicu-db-test.loadbalancer.server.port=5432
      - traefik.docker.network=proxy
